// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPpbErB0lrEn2gajwu0Fk6cITeaTC3rbg',
    appId: '1:385202973743:web:4b3b97c51238a49f08eada',
    messagingSenderId: '385202973743',
    projectId: 'finance-tracker-cd6a2',
    authDomain: 'finance-tracker-cd6a2.firebaseapp.com',
    storageBucket: 'finance-tracker-cd6a2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdFwLnmLnKD8XVB_3HnzWc2k-oOpmspxI',
    appId: '1:385202973743:android:4e1e613b4b2361a608eada',
    messagingSenderId: '385202973743',
    projectId: 'finance-tracker-cd6a2',
    storageBucket: 'finance-tracker-cd6a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvMddZ8woctl4ZVg8Ompok13kS4gNbySM',
    appId: '1:385202973743:ios:59e9ce7bcf35ffe908eada',
    messagingSenderId: '385202973743',
    projectId: 'finance-tracker-cd6a2',
    storageBucket: 'finance-tracker-cd6a2.appspot.com',
    iosClientId: '385202973743-1mvsvm9jpkp5js119demhf4bdet5hehk.apps.googleusercontent.com',
    iosBundleId: 'com.example.financeTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvMddZ8woctl4ZVg8Ompok13kS4gNbySM',
    appId: '1:385202973743:ios:1c332dd505c2430908eada',
    messagingSenderId: '385202973743',
    projectId: 'finance-tracker-cd6a2',
    storageBucket: 'finance-tracker-cd6a2.appspot.com',
    iosClientId: '385202973743-ns9o3v6i83ur7h93ig8nm3bvmkslbar3.apps.googleusercontent.com',
    iosBundleId: 'com.example.financeTracker.RunnerTests',
  );
}
